#!/usr/bin/env python3
"""gen.py -- write f12test.c (a Tiny-C program exercising CSP 100..134, the
12-byte floating point procedures) and f12test.expect (what C's printf
gives for the same operations on IEEE doubles)."""
import struct, math

def words(x):
    b = struct.pack('<d', x) + b'\0' * 4
    w = [b[2 * k] | (b[2 * k + 1] << 8) for k in range(6)]
    return ', '.join(str(v - 65536 if v > 32767 else v) for v in reversed(w))   # pushed w5 first

C = ['/* f12test.c -- generated by gen.py: CSP 100..134 */', '#include <stdio.h>', '#include <string.h>',
     'char buf[48];', 'char num[16];', 'long l;', 'float f;', 'int main(void)', '{', '    int n;']
E = []
def show(expr_stmts, expect, fmt='g', prec=17):
    C.extend('    ' + s + ';' for s in expr_stmts)
    C.append("    __cspv(133, '%s', %d, buf);" % (fmt, prec))
    C.append('    printf("%s\\n", buf);')
    E.append(expect)
def g(x, prec=17): return '%.*g' % (prec, x)

a, b = 1.0 / 3.0, 2.5
for n, op, r in ((100, '+', a + b), (101, '-', a - b), (102, '*', a * b), (103, '/', a / b)):
    show(['__cspv(%d, %s, %s)' % (n, words(a), words(b))], g(r))
show(['__cspv(104, %s)' % words(a)], g(-a))
for n, fn in ((112, math.sqrt), (113, math.sin), (114, math.cos), (115, math.tan), (118, math.atan),
              (120, math.exp), (121, math.log), (122, math.log10), (128, math.sinh), (129, math.cosh), (130, math.tanh)):
    show(['__cspv(%d, %s)' % (n, words(0.5))], g(fn(0.5)))
show(['__cspv(116, %s)' % words(0.5)], g(math.asin(0.5)))
show(['__cspv(117, %s)' % words(0.5)], g(math.acos(0.5)))
show(['__cspv(124, %s)' % words(-2.5)], g(math.floor(-2.5)))
show(['__cspv(125, %s)' % words(-2.5)], g(math.ceil(-2.5)))
show(['__cspv(126, %s)' % words(-2.5)], g(abs(-2.5)))
show(['__cspv(119, %s, %s)' % (words(1.0), words(-1.0))], g(math.atan2(1.0, -1.0)))
show(['__cspv(123, %s, %s)' % (words(2.0), words(0.5))], g(2.0 ** 0.5))
show(['__cspv(127, %s, %s)' % (words(7.5), words(2.0))], g(math.fmod(7.5, 2.0)))
show(['__cspv(131, %s, 10)' % words(0.75)], g(math.ldexp(0.75, 10)))
# conversions
show(['__cspv(108, -1234)'], '-1234')
show(['l = 100000L; __cspv(110, l)'], '100000')
show(['f = 0.1; __cspv(106, f)'], g(struct.unpack('<f', struct.pack('<f', 0.1))[0] if False else 0.100000001490116119384765625, 17))
show(['__cspv(107, %s); __cspv(106)' % words(math.pi)], g(3.1415925025939941))
C.append('    n = __cspi(109, %s);' % words(-7.9)); C.append('    printf("%d\\n", n);'); E.append('-7')
C.append('    n = __cspi(105, %s, %s);' % (words(1.0), words(2.0))); C.append('    printf("%d\\n", n);'); E.append('-1')
C.append('    n = __cspi(105, %s, %s);' % (words(2.0), words(2.0))); C.append('    printf("%d\\n", n);'); E.append('0')
show(['__cspv(111, %s); __cspv(110)' % words(-123456.9)], '-123456')
# formats
show(['__cspv(0 + 100, %s, %s)' % (words(1e300), words(1e300))], '%.6e' % 2e300, 'e', 6)
show(['__cspv(126, %s)' % words(3.14159265358979)], '%.4f' % 3.14159265358979, 'f', 4)
# ATOD: "12.5x" -> 12.5 and 4 characters, fed to DLDEXP: 12.5 * 2^4
C.append('    num[0] = 0; strcpy(num, "12.5x");')
show(['__cspv(134, num); __cspv(131)'], g(12.5 * 16))
C.append('    return 0;'); C.append('}')
open('f12test.c', 'w').write('\n'.join(C) + '\n')
open('f12test.expect', 'w').write('\n'.join(E) + '\n')
print('wrote f12test.c, f12test.expect (%d checks)' % len(E))
